## Connection to Thymio

In [1]:
# Connect to Thymio with ClientAsync
from tdmclient import ClientAsync, aw
client = ClientAsync()
node = await client.wait_for_node()

# Lock Thymio
aw(node.lock())

Node 52ceb7f5-6164-4bf6-b28a-33899f775678

## Importation of libraries

In [2]:
from kalman_filtering.kalman_filter import *
from thymio.control import *
from computer_vision.vision import *
from path_planning.path_plan import *
from navigation.collision_avoidance import *

## Main script

In [3]:
map = Map()
if P_VISION:
    print(P_SETUP)
    print("Place the Thymio and the destination, check the obstacles and the corners. Then, press S.")

while True:
    map.update(True)
    cv.waitKey(0)
    if cv.waitKey(20) & 0xFF==ord('s'):
        if map.get_found_corners():
            map.update()
            break
        elif P_VISION:
            print("USER: Must find corners before start")

if P_VISION: print(P_START)
if P_VISION: map.info()
await node.wait_for_variables()

u_old = np.zeros(2)
mu_predict_old = np.array([map.robot[0], map.robot[1], u_old[0], u_old[1]])
cov_predict_old = 100*np.eye(4)
view_blocked = False
active = True
end = False
start = True
path = None
segment_index = 0
obstacle = 0

#print("mu_predict_old:", mu_predict_old)

while active == True:
    active = await stop_thymio(node)

    map.update()
    
    # State variables measurement
    await node.wait_for_variables()
    vel_meas = velocity_with_odometry(node, map.robot[2])

    # Filtering
    y = np.array([map.robot[0], map.robot[1], vel_meas[0], vel_meas[1]])
    x_est, cov_est = kalman_filter(y, u_old, mu_predict_old, cov_predict_old, map.found_robot)
    map.pose_est = np.array([int(x_est[0]), int(x_est[1]), np.arctan2(x_est[3], x_est[2])])
    error_est = np.array([cov_est[0,0], cov_est[1,1], 0])
    print("Pose estimation of the Thymio:", map.pose_est)
   
    # Global Navigation
    if start == True:
        ex_path, corners = compute_visibility_matrix(map.robot[0:2], map.destination[0:2], map.obstacles)
        map.obstacles_lines = possible_lignes(ex_path, corners)
        map.target_lines = a_star_search(corners, ex_path)
        path = path_functions(map.target_lines)
        start = False

    # Local Navigation
    u, obstacle, segment = await collision_avoidance(path, segment_index, map.robot, node) # Zacharie

    if not obstacle:
        u, segment_index, end = path_direction(map.robot, path, segment_index)

    await node.set_variables(motors(int(u[0]), int(u[1])))

    u_old = u
    cov_predict_old = cov_est
    mu_predict_old = x_est
    # obstacle_old = obstacle

    if cv.waitKey(20) & 0xFF==ord('p'):
        map.vision_stop()
        break

=====[   SETUP      ]===============
Place the Thymio and the destination, check the obstacles and the corners. Then, press S.
[0 0]
[0 0]
[0 0]
=====[   START      ]===============
=====[   MAP INFO   ]===============
* FOUND CORNERS: True

* FOUND ROBOT: True
Position: [44, 112]
Orientation: 0.5121052581844701

* FOUND DESTINATION: True
Position: [583, 361]

* OBSTACLES: 2

[0 0]
[ 4.30000000e+01  1.13000000e+02 -1.84338093e-09  1.84338094e-09]
Pose estimation of the Thymio: [ 43.         112.           2.35619449]
Path_reached
[ 43. 112.]
[ 44.         112.          79.23467172  75.0895757 ]
Pose estimation of the Thymio: [ 44.         112.           0.75854496]
Path_reached
[ 44. 112.]
[ 44.         113.         154.23020212 145.45199085]
Pose estimation of the Thymio: [ 44.        113.          0.7561148]
Path_reached
[ 44. 113.]
[ 50.         117.         249.59786688 226.55221319]
Pose estimation of the Thymio: [ 50.         117.           0.73703593]
Path_reached
[ 50. 117.]
[ 

TypeError: cannot unpack non-iterable NoneType object

## Thymio velocity measurements

In [ ]:
active = True
vel_meas = []

while active:
    await node.wait_for_variables()
    await node.set_variables(motors(100, 100))
    vel_meas.append(velocity_with_odometry(node, 0)[0])
    active = await stop_thymio(node)

await node.set_variables(motors(0, 0)) 

vel_meas_mean = np.mean(vel_meas[10:])
vel_meas_var = np.var(vel_meas[10:])
print("Length of vel_meas:", len(vel_meas))
print("Velocity measured:", vel_meas[10:])
print("Velocity mean:", vel_meas_mean)
print("Velocity variance:", vel_meas_var)

Center button pressed. Stopping the algorithm.
Length of vel_meas: 20
Velocity measured: [99.0, 99.0, 99.0, 95.0, 95.0, 99.0, 99.0, 99.0, 99.0, 100.0]
Velocity mean: 98.3
Velocity variance: 2.81


In [ ]:
import time

timer = 0
start = time.time()

while timer < 10:
    await node.set_variables(motors(97, 100))
    timer = time.time() - start

await node.set_variables(motors(0, 0))

In [ ]:
robot_vel = np.array([3.35,3.36,3.35,3.39,3.36,3.33,3.34,3.38,3.42,3.41])

robot_vel_mean = np.mean(robot_vel)
robot_vel_var = np.var(robot_vel)

print("Robot velocity mean:", robot_vel_mean)
print("Robot velocity variance:", robot_vel_var)

Robot velocity mean: 3.3689999999999998
Robot velocity variance: 0.0008090000000000007


## Thymio position measurements

In [ ]:
map = Map()

robot_positions_x = []
robot_positions_y = []
map.update(True)
while True:
    map.update()
    robot_position_x = map.robot[0]
    robot_position_y = map.robot[1]
    robot_positions_x.append(robot_position_x)
    robot_positions_y.append(robot_position_y)
    if cv.waitKey(20) & 0xFF==ord("d"):
        map.vision_stop()
        break

robot_positions_x_mean = np.mean(robot_positions_x[10:])
robot_positions_x_var = np.var(robot_positions_x[10:])
robot_positions_y_mean = np.mean(robot_positions_y[10:])
robot_positions_y_var = np.var(robot_positions_y[10:])

print("Position x measured:", robot_positions_x[10:])
print("Position x mean:", robot_positions_x_mean)
print("Position x variance:", robot_positions_x_var)

print("Position y measured:", robot_positions_y[10:])
print("Position y mean:", robot_positions_y_mean)
print("Position y variance:", robot_positions_y_var)

=====[   STOP       ]===============
Position x measured: [184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 1

In [ ]:
node.var

{'_fwversion': [14, 0],
 '_id': [-27410],
 '_imot': [-17, -189],
 '_integrator': [689, -1116],
 '_productId': [8],
 '_vbat': [718, 717],
 'acc': [1, -1, 24],
 'acc._tap': [32],
 'button.backward': [0],
 'button.center': [1],
 'button.forward': [0],
 'button.left': [0],
 'button.right': [0],
 'buttons._mean': [10655, 9142, 13730, 13675, 15078],
 'buttons._noise': [57, 46, 60, 53, 80],
 'buttons._raw': [10641, 9140, 13538, 13663, 15020],
 'event.args': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'event.source': [-27410],
 'leds.bottom.left': [0, 0, 0],
 'leds.bottom.right': [0, 0, 0],
 'leds.circle': [0, 0, 0, 0, 0, 0, 0, 0],
 'leds.top': [0, 0, 0],
 'mic._mean': [261],
 'mic.intensity': [29],
 'mic.threshold': [0],
 'motor.left.pwm': [329],
 'motor.left.speed': [-72],
 'motor.left.target': [-100],
 'motor.right.pwm': [-419],
 'motor.right.speed': [100],
 'motor.right.targ